'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
type Setup={planVariationId:string|null;planValid:boolean;planConfigured:boolean;webhookReady:boolean;enrollmentEnabled:boolean;recurringEnabled:boolean;checkedAt:string};
async function call(prepare=false):Promise<Setup>{
 const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in with your Hometown Perks owner account.');
 const response=await fetch('/api/admin/billing-setup',{method:prepare?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,...(prepare?{'Content-Type':'application/json'}:{})},...(prepare?{body:JSON.stringify({action:'prepare'})}:{})});
 const result=await response.json();if(!response.ok)throw Error(result.error??'Configuration unavailable.');return result;
}
export default function BillingSetupPage(){
 const [data,setData]=useState<Setup|null>(null),[message,setMessage]=useState('Checking production billing configuration…'),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;call().then(result=>{if(active){setData(result);setMessage('');}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[]);
 async function run(prepare:boolean){setBusy(true);setMessage(prepare?'Preparing the monthly catalog plan and billing notifications…':'Checking configuration…');try{setData(await call(prepare));setMessage(prepare?'Configuration prepared. This does not start subscriptions or open enrollment.':'Configuration refreshed.');}catch(error){setMessage(error instanceof Error?error.message:'Configuration unavailable.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-950 text-white p-6"><div className="max-w-3xl mx-auto py-10"><a className="text-blue-300" href="/admin">Merchant Management</a><h1 className="text-3xl font-bold my-6">Production billing setup</h1><p>Prepare a fixed $149 USD monthly catalog plan and add subscription and invoice events to the portal’s existing Square webhook. This does not charge anyone, create a merchant subscription, change host agreements or open enrollment.</p><p role="status" className="my-5">{message}</p><button disabled={busy||!data} onClick={()=>void run(true)} className="bg-blue-600 p-3 rounded mr-4 disabled:opacity-50">Prepare billing configuration</button><button disabled={busy} onClick={()=>void run(false)} className="border p-3 rounded disabled:opacity-50">{busy?'Working…':'Refresh configuration'}</button>{data&&<section className="my-6 p-5 bg-slate-800 rounded"><p>Monthly $149 plan verified: {data.planValid?'Yes':'Not configured'}</p><p>Plan connected to portal: {data.planConfigured?'Yes':'Pending deployment configuration'}</p><p>Subscription and invoice notifications: {data.webhookReady?'Ready':'Incomplete'}</p><p>Paid enrollment: {data.enrollmentEnabled?'Enabled by environment':'Closed by environment'}</p><p>Monthly activation: {data.recurringEnabled?'Enabled':'Closed for testing'}</p>{data.planVariationId&&<p className="break-all mt-4">Monthly plan variation ID: <code>{data.planVariationId}</code></p>}<p className="mt-4 text-sm">Checked: {data.checkedAt}</p></section>}</div></main>;
}
