const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript');
function load(path,mocks={}){const m=new Module(path,module);m.paths=module.paths;const req=m.require.bind(m);m.require=n=>mocks[n]??req(n);m._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,path);return m.exports;}
const inquiry=load('lib/inquiries.ts'),body={requestId:'11111111-1111-4111-8111-111111111111',business:'Example',contact:'Test',email:'TEST@example.com',phone:'',area:'Pikeville',message:'',plate:false,website:'',consent:true};
function api(db){return load('app/api/inquiries/route.ts',{'@/lib/billing/server':{database:()=>db},'@/lib/inquiries':inquiry});}
function request(value=body,origin='https://www.hometownperksusa.com'){return new Request('https://portal.example/api/inquiries',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(value)});}
test('intake rejects other origins and does not touch the database',async()=>{const route=api({rpc(){throw Error('Forbidden');}});assert.equal((await route.POST(request(body,'https://other.example'))).status,403);assert.equal(route.OPTIONS(request(body,'https://other.example')).status,403);});
test('validation rejects missing consent, invalid email, overlong fields, honeypots and invalid IDs',()=>{for(const update of [{consent:false},{email:'invalid'},{business:'x'.repeat(151)},{website:'bot.example'},{requestId:'fake'},{plate:'yes'},{contact:''}])assert.equal(inquiry.validateInquiry({...body,...update}),null);assert.equal(inquiry.validateInquiry(body).email,'test@example.com');});
test('success is returned only after the database confirms persistence; no payment or merchant operation runs',async()=>{let args;const route=api({rpc:async(name,value)=>{args={name,value};return {data:'saved'};}});const response=await route.POST(request());assert.equal(response.status,200);assert.deepEqual(await response.json(),{saved:true});assert.equal(response.headers.get('access-control-allow-origin'),'https://www.hometownperksusa.com');assert.equal(args.name,'save_advertiser_inquiry');assert.equal(args.value.p_id,body.requestId);assert.equal(args.value.p_email,'test@example.com');});
test('database failures and rate limits never pretend the inquiry was saved',async()=>{for(const [result,status] of [[{error:{message:'secret'}},503],[{data:'limited'},429],[{data:null},503]]){const response=await api({rpc:async()=>result}).POST(request());assert.equal(response.status,status);assert.equal((await response.json()).saved,undefined);}});
test('oversized streamed request is rejected before accessing the database',async()=>{const response=await api({rpc(){throw Error('Forbidden');}}).POST(request({...body,message:'x'.repeat(10000)}));assert.equal(response.status,413);});
test('inquiry inbox rejects non-owners before accessing contacts',async()=>{const route=load('app/api/admin/inquiries/route.ts',{'@/lib/billing/server':{adminFor:async()=>null,database(){throw Error('Forbidden');}}});const response=await route.GET(new Request('https://portal.example/api/admin/inquiries'));assert.equal(response.status,403);assert.equal(response.headers.get('cache-control'),'private, no-store');});
