'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {documentRequest,openDocument,type MerchantDocument} from '@/lib/documents/client';
type Merchant={id:string;businessName:string|null;email:string|null;accountLinked:boolean};
export default function AdminDocumentsPage(){
 const [merchants,setMerchants]=useState<Merchant[]>([]),[merchantId,setMerchantId]=useState(''),[documents,setDocuments]=useState<MerchantDocument[]>([]),[message,setMessage]=useState('Checking owner access…'),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;documentRequest('/api/admin/documents'+(merchantId?`?merchantId=${encodeURIComponent(merchantId)}`:'')).then(result=>{if(active){setMerchants(result.merchants);setDocuments(result.documents);setLoaded(true);setMessage('');}}).catch(error=>{if(active){setLoaded(false);setMessage(error.message);}});return()=>{active=false;};},[merchantId,attempt]);
 const selected=merchants.find(m=>m.id===merchantId);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=new FormData(form),file=fields.get('file');if(!(file instanceof File)||file.size>3*1024*1024){setMessage('Choose a PDF no larger than 3 MB.');return;}setBusy(true);setMessage('Uploading the document…');try{fields.set('merchantId',merchantId);await documentRequest('/api/admin/documents',fields);const result=await documentRequest(`/api/admin/documents?merchantId=${encodeURIComponent(merchantId)}`);setDocuments(result.documents);form.reset();setMessage('Document uploaded and attached to this merchant.');}catch(error){setMessage(error instanceof Error?error.message:'Upload unavailable.');}finally{setBusy(false);}}
 async function open(id:string,download:boolean){setBusy(true);try{await openDocument(id,download);}catch(error){setMessage(error instanceof Error?error.message:'Unable to open document.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-950 text-white p-6 sm:p-10"><div className="max-w-3xl mx-auto py-8"><Link className="text-blue-300" href="/admin">Merchant Management</Link><h1 className="text-3xl font-bold my-6">Merchant Agreements &amp; Documents</h1><p className="text-slate-300">Upload the finalized signed PDF from Square to the correct merchant. The merchant can view and download it after signing in. Uploading does not activate advertising or change billing.</p>{message&&<p role="status" className="my-5">{message}</p>}<label className="block my-6">Merchant<select value={merchantId} disabled={busy||!loaded} onChange={e=>{setMerchantId(e.target.value);setDocuments([]);setLoaded(false);setMessage('Loading merchant documents…');}} className="block bg-slate-800 rounded p-3 w-full mt-2"><option value="">Select a merchant</option>{merchants.map(m=><option key={m.id} value={m.id}>{m.businessName||'Unnamed merchant'}{m.email?` — ${m.email}`:''}</option>)}</select></label>{selected&&<><p className="mb-5">Selected: <strong>{selected.businessName||'Unnamed merchant'}</strong>{selected.email?` · ${selected.email}`:''}</p>{!selected.accountLinked&&<p className="my-5 rounded bg-amber-950 p-4">This merchant does not have a linked portal login yet. You can save documents now; they become available after the merchant’s login is linked.</p>}<form onSubmit={event=>void upload(event)} className="bg-slate-800 rounded-xl p-6"><label className="block mb-5">Document title<input name="title" required maxLength={160} placeholder="Signed advertising agreement" className="block bg-slate-900 rounded p-3 w-full mt-2"/></label><label className="block mb-5">Signed PDF (up to 3 MB)<input type="file" name="file" required accept="application/pdf,.pdf" className="block mt-3 w-full"/></label><label className="block mb-5"><input type="checkbox" required/> I verified this document belongs to the selected merchant and is the copy I want them to access.</label><button disabled={busy||!loaded} className="bg-blue-600 rounded px-5 py-3 disabled:opacity-50">{busy?'Working…':'Upload to merchant account'}</button></form><h2 className="text-2xl font-semibold my-6">Attached documents</h2>{loaded&&!documents.length&&<p>No documents attached yet.</p>}{documents.map(d=><section key={d.id} className="bg-slate-800 rounded-xl p-5 my-4"><h3 className="text-xl">{d.title}</h3><p className="text-slate-300 my-3">{d.file_name} · Added {new Date(d.created_at).toLocaleDateString()}</p><button disabled={busy} className="bg-blue-600 rounded p-3 mr-3 disabled:opacity-50" onClick={()=>void open(d.id,false)}>View PDF</button><button disabled={busy} className="border rounded p-3 disabled:opacity-50" onClick={()=>void open(d.id,true)}>Download PDF</button></section>)}</>}<button disabled={busy} className="text-blue-300 underline my-5 disabled:opacity-50" onClick={()=>{setMessage('Refreshing…');setAttempt(n=>n+1);}}>Refresh documents</button></div></main>;
}
