'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
type Inquiry={id:string;business_name:string;contact_name:string;email:string;phone:string;service_area:string;message:string;connect_plate_interest:boolean;created_at:string};
export default function InquiriesPage(){
 const [items,setItems]=useState<Inquiry[]>([]),[page,setPage]=useState(0),[total,setTotal]=useState(0),[attempt,setAttempt]=useState(0),[status,setStatus]=useState('Checking owner access…'),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;async function load(){setLoading(true);setStatus('Loading inquiries…');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in with your Hometown Perks owner account.');const response=await fetch(`/api/admin/inquiries?page=${page}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to load inquiries.');if(active){setItems(result.inquiries);setTotal(result.total);setStatus('');}}catch(error){if(active){setItems([]);setStatus(error instanceof Error?error.message:'Unable to load inquiries.');}}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[page,attempt]);
 return <main className="min-h-screen bg-slate-950 text-white p-6 sm:p-10"><div className="max-w-3xl mx-auto py-8"><Link className="text-blue-300" href="/admin">Merchant Management</Link><h1 className="text-3xl font-bold my-6">Advertiser Inquiries</h1><p className="text-slate-300">Businesses that expressed interest through your public website. An inquiry does not create a merchant account, enroll a business, or authorize a payment. Follow up when you are ready.</p>{status&&<p role="status" className="my-5">{status}</p>}<button disabled={loading} onClick={()=>setAttempt(n=>n+1)} className="my-5 rounded border px-4 py-2 disabled:opacity-50">Refresh inquiries</button>{!status&&!items.length&&<p>No inquiries yet.</p>}{items.map(item=><section key={item.id} className="my-5 rounded-xl bg-slate-800 p-6"><h2 className="text-xl font-semibold">{item.business_name}</h2><p className="text-slate-300 my-3">Received {new Date(item.created_at).toLocaleString()}</p><p>Contact: {item.contact_name}</p><p>Email: <a className="text-blue-300 underline" href={`mailto:${item.email}`}>{item.email}</a></p>{item.phone&&<p>Phone: {item.phone}</p>}<p>City / service area: {item.service_area}</p><p>Connect Plate interest: {item.connect_plate_interest?'Yes':'Not selected'}</p>{item.message&&<p className="mt-4 whitespace-pre-wrap break-words">{item.message}</p>}</section>)}{total>50&&<nav aria-label="Inquiry pages" className="flex gap-4 items-center"><button disabled={loading||page===0} onClick={()=>setPage(p=>p-1)} className="border rounded p-2 disabled:opacity-50">Previous</button><span>Page {page+1} of {Math.ceil(total/50)}</span><button disabled={loading||(page+1)*50>=total} onClick={()=>setPage(p=>p+1)} className="border rounded p-2 disabled:opacity-50">Next</button></nav>}</div></main>;
}
