'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
type Offer={enabled:boolean;amountCents?:number;termsVersion?:string;termsText?:string;launchDeadline?:string;locations?:string[]};
type Enrollment={status:string;launch_deadline:string;confirmed_locations:string[]};
export default function EnrollmentPage(){
 const [offer,setOffer]=useState<Offer|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signedIn,setSignedIn]=useState(false),[enrollment,setEnrollment]=useState<Enrollment|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[accept,setAccept]=useState(false);
 async function refresh(){const {data:{session}}=await supabase.auth.getSession();setSignedIn(!!session);if(session){const r=await fetch('/api/enrollment/status',{headers:{Authorization:`Bearer ${session.access_token}`}});const data=await r.json();setEnrollment(data.enrollment??null);}}
 useEffect(()=>{fetch('/api/enrollment/config').then(r=>r.json()).then(setOffer).catch(()=>setOffer({enabled:false}));const {data}=supabase.auth.onAuthStateChange((_event,session)=>{setSignedIn(!!session);if(!session){setEnrollment(null);return;}fetch('/api/enrollment/status',{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(d=>setEnrollment(d.enrollment??null)).catch(()=>setMessage('Enrollment status is unavailable.'));});return()=>data.subscription.unsubscribe();},[]);
 async function account(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const button=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement;if(button.value==='register'){const r=await fetch('/api/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();setMessage(d.message??d.error);}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage('Could not sign in. Check your email and password.');else await refresh();}}catch{setMessage('Account service is unavailable.');}finally{setBusy(false);}}
 async function checkout(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const fields=new FormData(event.currentTarget);const {data:{session}}=await supabase.auth.getSession();if(!session){setMessage('Sign in first.');return;}const r=await fetch('/api/enrollment/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({businessName:fields.get('businessName'),contactName:fields.get('contactName'),phone:fields.get('phone'),acceptTerms:accept,termsVersion:offer?.termsVersion})});const d=await r.json();if(r.ok&&d.url)window.location.assign(d.url);else setMessage(d.error??'Checkout is unavailable.');}catch{setMessage('Checkout is unavailable.');}finally{setBusy(false);}}
 const style='block w-full rounded-lg bg-slate-800 border border-slate-600 p-3 mt-2 mb-5';
 return <main className="min-h-screen bg-slate-950 text-white p-6"><div className="max-w-2xl mx-auto py-10"><a href="https://www.hometownperksusa.com" className="text-blue-300">Hometown Perks</a><h1 className="text-3xl font-bold mt-6 mb-6">Advertiser Enrollment</h1>
 {!offer?<p>Loading enrollment availability…</p>:!offer.enabled?<><p>Paid enrollment is not open yet. We’re preparing our screen network for launch.</p><a className="inline-block mt-6 text-blue-300 underline" href="https://www.hometownperksusa.com/merchant-signup">Express interest</a></>:<><p className="mb-5">Pay $149 upfront for your first 30 calendar days of advertising. Your service period begins when your approved ad goes live. Later $149 monthly renewals require your separate authorization. This payment does not begin a recurring subscription.</p><p>Launch deadline: {offer.launchDeadline}</p><p className="mt-3">Contracted locations: {offer.locations?.join(', ')}</p>
 {!signedIn?<form onSubmit={account} className="mt-8"><label>Email<input className={style} type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input className={style} type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button disabled={busy} value="login" className="bg-blue-600 p-3 rounded mr-4">Sign In</button><button disabled={busy} value="register" className="bg-slate-700 p-3 rounded">Create Account</button><p className="mt-3 text-sm">New accounts require a password of at least 12 characters and email confirmation before checkout.</p></form>:enrollment&&enrollment.status!=='awaiting_payment'?<div className="mt-8 border border-slate-700 p-5 rounded"><h2 className="text-xl">Enrollment status: {enrollment.status.replaceAll('_',' ')}</h2><p className="mt-3">Payment confirmation is separate from ad activation. Your ad does not start automatically when payment is received.</p><button className="mt-4 text-blue-300 underline" onClick={()=>void refresh()}>Refresh Status</button><a className="block mt-4 text-blue-300 underline" href="/dashboard">Merchant Dashboard</a><a className="block mt-4 text-blue-300 underline" href="/billing">Manage billing</a></div>:<form onSubmit={checkout} className="mt-8"><label>Business name<input name="businessName" required maxLength={150} className={style}/></label><label>Contact name<input name="contactName" required maxLength={150} className={style}/></label><label>Phone<input name="phone" type="tel" required maxLength={150} className={style}/></label><h2 className="text-xl font-semibold">Launch Terms</h2><div className="whitespace-pre-wrap border border-slate-700 rounded p-5 my-4">{offer.termsText}</div><label className="flex gap-3"><input type="checkbox" required checked={accept} onChange={e=>setAccept(e.target.checked)}/>I accept these launch terms and the $149 first-month advance payment.</label><button disabled={busy||!accept} className="bg-blue-600 disabled:opacity-50 p-4 rounded mt-6">Continue to Square — $149</button><p className="text-sm mt-4">Square processes your payment. Returning from checkout does not confirm payment; refresh this page to view its verified status.</p></form>}</>}
 {message&&<p role="status" className="mt-6 text-blue-200">{message}</p>}{enrollment&&!offer?.enabled&&<p className="mt-6">Your existing enrollment status: {enrollment.status.replaceAll('_',' ')}</p>}</div></main>;
}
