'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {documentRequest,openDocument,type MerchantDocument} from '@/lib/documents/client';
export default function DocumentsPage(){
 const [documents,setDocuments]=useState<MerchantDocument[]|null>(null),[message,setMessage]=useState('Loading your documents…'),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;documentRequest('/api/merchant/documents').then(result=>{if(active){setDocuments(result.documents);setMessage('');}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[attempt]);
 async function open(id:string,download:boolean){setBusy(true);setMessage('Opening your document…');try{await openDocument(id,download);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Unable to open document.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-950 text-white p-6 sm:p-10"><div className="max-w-3xl mx-auto py-8"><Link className="text-blue-300" href="/dashboard">Merchant Dashboard</Link><h1 className="text-3xl font-bold my-6">Agreements &amp; Documents</h1><p className="text-slate-300">View and download the documents Hometown Perks has attached to your account.</p>{message&&<p role="status" className="my-5">{message}</p>}{documents?.length===0&&<p className="my-8 rounded-xl bg-slate-800 p-6">No documents have been attached to your account yet.</p>}{documents?.map(d=><section key={d.id} className="my-5 bg-slate-800 rounded-xl p-6"><h2 className="text-xl font-semibold">{d.title}</h2><p className="text-slate-300 my-3">{d.file_name} · Added {new Date(d.created_at).toLocaleDateString()} · PDF</p><button disabled={busy} onClick={()=>void open(d.id,false)} className="bg-blue-600 rounded px-4 py-3 mr-4 disabled:opacity-50">View PDF</button><button disabled={busy} onClick={()=>void open(d.id,true)} className="border rounded px-4 py-3 disabled:opacity-50">Download PDF</button></section>)}<button disabled={busy} className="text-blue-300 underline my-5 disabled:opacity-50" onClick={()=>{setMessage('Loading your documents…');setAttempt(n=>n+1);}}>Refresh documents</button></div></main>;
}
