'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
type Run={id:string;stage:string;live_date:string;renewal_start_date:string;payment_status?:string;refund_status?:string;subscription_status?:string;webhook_payment_seen_at?:string;webhook_refund_seen_at?:string;last_error_code?:string;card_removed?:boolean;cancellation_scheduled?:boolean;cancellation_date?:string;provider_checked_at?:string;provider_check_error?:boolean};
async function call(runId?:string){
 const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in with your Hometown Perks owner account.');
 const r=await fetch('/api/admin/sandbox-test',{method:runId?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,...(runId?{'Content-Type':'application/json'}:{})},...(runId?{body:JSON.stringify({runId})}:{})});const d=await r.json();if(!r.ok)throw Error(`${d.error}${d.stage?` Stage: ${d.stage}.`:''}`);return d;
}
export default function SandboxPage(){
 const [runs,setRuns]=useState<Run[]>([]),[configured,setConfigured]=useState(false),[message,setMessage]=useState('Checking sandbox configuration…'),[busy,setBusy]=useState(false);
 useEffect(()=>{call().then(d=>{setRuns(d.runs);setConfigured(d.configured);setMessage(d.configured?'':'Square sandbox credentials have not been connected yet.');}).catch(e=>setMessage(e.message));},[]);
 async function refresh(){const d=await call();setRuns(d.runs);setConfigured(d.configured);}
 async function refreshResults(){setBusy(true);setMessage('Checking current Square sandbox records…');try{await refresh();setMessage('Results refreshed. See the Square check time or warning below. No new payment was created.');}catch(e){setMessage(e instanceof Error?e.message:'Results could not be refreshed.');}finally{setBusy(false);}}
 async function run(id=crypto.randomUUID()){setBusy(true);setMessage('Running a Square sandbox test…');try{await call(id);await refresh();setMessage('Sandbox API steps completed. Refresh to check delivery of signed payment and refund webhooks.');}catch(e){setMessage(e instanceof Error?e.message:'Sandbox test unavailable.');await refresh().catch(()=>{});}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-950 text-white p-6"><div className="max-w-3xl mx-auto py-10"><a href="/admin" className="text-blue-300">Merchant Management</a><h1 className="text-3xl font-bold my-6">Square Sandbox Verification</h1><p>This owner-only test uses Square’s sandbox and fictional payment data. It tests a $149 payment, payment replay, a stored test card, a monthly subscription starting after 30 calendar days, cancellation, and a refund. It does not enroll a real merchant or change host agreements.</p><p role="status" className="my-5">{message}</p><button disabled={busy||!configured} onClick={()=>void run()} className="bg-blue-600 p-3 rounded mr-4 disabled:opacity-50">Run sandbox test</button><button disabled={busy} onClick={()=>void refreshResults()} className="border p-3 rounded disabled:opacity-50">{busy?'Working…':'Refresh results'}</button>
 {runs.map(r=><section key={r.id} className="my-6 p-5 bg-slate-800 rounded"><h2 className="text-xl">API test stage: {r.stage.replaceAll('_',' ')}</h2><p className="text-sm my-2">Run {r.id}</p><p>Test launch date: {r.live_date} · First renewal: {r.renewal_start_date}</p><p>Payment: {r.payment_status??'Not tested'} · Refund: {r.refund_status??'Not tested'} · Subscription: {r.subscription_status??'Not tested'}</p><p>Signed payment webhook: {r.webhook_payment_seen_at?'Received':'Not yet received'}</p><p>Signed refund webhook: {r.webhook_refund_seen_at?'Received':'Not yet received'}</p>{r.provider_checked_at&&<><p>Test card removed: {r.card_removed===undefined?'Not tested':r.card_removed?'Yes':'No'}</p><p>Cancellation scheduled or completed: {r.cancellation_scheduled===undefined?'Not tested':r.cancellation_scheduled?'Yes':'No'}{r.cancellation_date?` · Square cancellation date: ${r.cancellation_date}`:''}</p><p className="text-sm mt-2">Square records checked: {r.provider_checked_at}</p></>}{r.provider_check_error&&<p className="text-amber-300">Square could not be checked. Payment, refund and subscription labels above are saved values, not current verification.</p>}{r.refund_status==='PENDING'&&<p className="mt-2">The refund has been requested but has not completed. Receiving its webhook does not confirm completion.</p>}{r.last_error_code&&<p>Last error: {r.last_error_code}</p>}{r.stage!=='completed'&&<button disabled={busy||!configured} onClick={()=>void run(r.id)} className="mt-3 border p-3 rounded">Retry this run</button>}</section>)}</div></main>;
}
